apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: data-platform
type: Opaque
data:
  # Default credentials: minioadmin/minioadmin
  MINIO_ROOT_USER: bWluaW9hZG1pbg==
  MINIO_ROOT_PASSWORD: bWluaW9hZG1pbg==