apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: data-platform
type: Opaque
data:
  POSTGRES_PASSWORD: ZXRscGFzc3dvcmQ=  # Base64 encoded 'etlpassword'
  POSTGRES_USER: ZXRsdXNlcg==  # Base64 encoded 'etluser'